version: '3'
services:
  go:
    build:
      context: ./go-workspace/.devcontainer
      args:
        - "--cap-add=SYS_PTRACE"
        - "--security-opt"
        - "seccomp=unconfined"
    volumes:
      - .:/workspace:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
  python:
    build:
      context: ./python-workspace/.devcontainer
    volumes:
      - .:/workspace:cached
    command: /bin/sh -c "while sleep 1000; do :; done"